language: node_js
node_js:
  - "node"
before_install:
  - npm install -g npm@latest
script:
  - npm run docs
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
